- hosts: localhost
  gather_facts: false

  vars:
  - IPA_DOMAIN: pbs.toy
  - SUBNET_PREFIX: 10.20.24
  - nodes:
    - name: torque
    - name: node1
    - name: node2
    - name: node3
    - name: node4

  tasks:

  - file: state=directory path=/data/volume/{{ IPA_DOMAIN }}/home

  - name: Create Compute nodes and TORQUE server podman containers for domain "{{ IPA_DOMAIN }}"
    containers.podman.podman_container:
      name: "{{ item.name }}.{{ IPA_DOMAIN }}"
      hostname: "{{ item.name }}.{{ IPA_DOMAIN }}"
      recreate: true
      privileged: true
      rm: false
      tty: true
      interactive: true
      detach: true
      network: "podman.{{ IPA_DOMAIN }}"
      dns: "{{ SUBNET_PREFIX }}.253"
      dns_search: "{{ IPA_DOMAIN }}"
      volume:
        - /data/volume/{{ IPA_DOMAIN }}/home:/home
      image: rockylinux/rockylinux:9-ubi-init
      generate_systemd:
        path: /tmp/
        new: true
        container_prefix: ipaclients
    with_items: "{{ nodes }}"

  - containers.podman.podman_container:
      name: "login.{{ IPA_DOMAIN }}"
      hostname: "login.{{ IPA_DOMAIN }}"
      publish: "2025:22"
      recreate: true
      privileged: true
      rm: false
      tty: true
      interactive: true
      detach: true
      network: "podman.{{ IPA_DOMAIN }}"
      dns: "{{ SUBNET_PREFIX }}.253"
      dns_search: "{{ IPA_DOMAIN }}"
      volume:
        - /data/volume/{{ IPA_DOMAIN }}/home:/home
      image: rockylinux/rockylinux:9-ubi-init
      generate_systemd:
        path: /tmp/
        new: true
        container_prefix: ipaclients
