torque_mom_nodes:
  hosts:
    node[1:4].pbs.toy:
      ansible_connection: podman

torque_client_nodes:
  hosts:
    login.pbs.toy:
      ansible_connection: podman

torque_server_nodes:
  hosts:
    torque.pbs.toy:
      ansible_connection: podman

ipa_server_nodes:
  hosts:
    ipa.pbs.toy:
      ansible_connection: podman

container_host:
  hosts:
    localhost:
      ansible_connection: local

el9:
  children:
    torque_server_nodes:
    torque_client_nodes:
    torque_mom_nodes:

ipa_client_nodes:
  children:
    torque_server_nodes:
    torque_client_nodes:
    torque_mom_nodes:
